name: Run E2E test

on:
  workflow_dispatch:
    inputs:
      APP_DIR:
        required: true
        type: choice
        options:
          - www
          - app
          - admin
  workflow_call:
    inputs:
      APP_DIR:
        required: true
        type: string

jobs:
  e2e:
    name: E2E test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment:
      name: e2e
      url: ${{ steps.artifact-upload-step.outputs.artifact-url }}
    env:
      APP_DIR: ${{ inputs.APP_DIR }}
    steps:
      - uses: actions/checkout@v4
      - name: Install pocketbase
        run: |
          wget https://github.com/pocketbase/pocketbase/releases/download/v0.22.17/pocketbase_0.22.17_linux_amd64.zip -O /tmp/pb.zip
          unzip /tmp/pb.zip -d ./database/
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build app
        run: yarn _build

      - name: Cache playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: yarn playwright install --with-deps

      - name: Run Playwright tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v4
        id: artifact-upload-step
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
