name: Deploy DB on Fly
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/database/**"
      - .github/workflows/deploy-db.yaml

jobs:
  deploy-db:
    name: Deploy database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd apps/database; flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DB_API_TOKEN }}
