name: APP
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  # e2e:
  #   uses: ./.github/workflows/_e2e-test.yaml
  #   with:
  #     APP_DIR: app

  deploy:
    name: Deploy
    # needs: e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --config apps/app/fly.toml --dockerfile apps/app/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_APP_TOKEN }}
